alias test-build="docker build -t ticketing-hsg /workspaces/ticketing-hsg"
alias test-run="docker run -d --rm --network host --env-file /workspaces/ticketing-hsg/.devcontainer/dev.env --name ticketing-hsg ticketing-hsg"
alias test-run-attached="docker run --rm --network host --env-file /workspaces/ticketing-hsg/.devcontainer/dev.env --name ticketing-hsg ticketing-hsg"
alias test-run-stop="docker stop ticketing-hsg"
alias test-update="test-run-stop; test-build; test-run"