version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    volumes:
      - ../..:/workspaces:cached
      - ./aliases.sh:/home/vscode/.bash_aliases
    networks:
      - dev_network
    command: sleep infinity

  postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    networks:
      - dev_network
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "8443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - dev_network
    depends_on:
      - devcontainer

networks:
  dev_network:
    name: dev_network
    driver: bridge

volumes:
  postgres-data: