version: '3.8'
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    ports:
      - "8080:80"
    volumes:
      - ../..:/workspaces:cached
      - ./aliases.sh:/home/vscode/.bash_aliases
    command: sleep infinity

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    network_mode: service:devcontainer
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres